name: Deployment train production

on: 'workflow_dispatch'

jobs:
  check_version_back:
    name: Check version back
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de back'
        id: back_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/back
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '1.0.3'
        run: |
          if [ "$prod_version" == "${{ steps.back_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse back::La última versión del backend ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  check_version_front:
    name: Check version front
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de front'
        id: front_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/front
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '0.0.0'
        run: |
          if [ "$prod_version" == "${{ steps.front_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse Front::La última versión de Front ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  check_version_app:
    name: Check version app
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de app'
        id: webapp_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/app
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '1.0.0'
        run: |
          if [ "$prod_version" == "${{ steps.webapp_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse App::La última versión de la app ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  deploy_back:
    name: Deploy back
    needs: check_version_back
    if: ${{ needs.check_version_back.outputs.deploy == 'true' }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front:
    name: Deploy front
    needs: [check_version_front, deploy_back]
    if: ${{ needs.check_version_front.outputs.deploy == 'true' }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app:
    name: Deploy app
    needs: [check_version_app, deploy_front, deploy_back]
    if: ${{ needs.check_version_app.outputs.deploy == 'true' }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main
