name: Deployment train production

on: 'workflow_dispatch'

jobs:
  check_version_back:
    name: Check version back
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de back'
        id: back_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/back
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '1.0.3'
        run: |
          if [ "$prod_version" == "${{ steps.back_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse back::La última versión del backend ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  check_version_front:
    name: Check version front
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de front'
        id: front_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/front
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '0.0.0'
        run: |
          if [ "$prod_version" == "${{ steps.front_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse Front::La última versión de Front ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  check_version_app:
    name: Check version app
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    outputs:
      deploy: ${{ steps.set_output.outputs.deploy }}

    steps:
      - name: 'Obtener última release de app'
        id: webapp_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: test-ci-workflows-israel/app
          excludes: 'prerelease, draft'

      - name: 'Echo version'
        id: set_output
        env:
          prod_version: '1.0.0'
        run: |
          if [ "$prod_version" == "${{ steps.webapp_release.outputs.release }}" ]; then
            echo "deploy=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=No va a desplegarse App::La última versión de la app ya está desplegada en producción"
          else
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi

  deploy_back:
    name: Deploy back
    needs: check_version_back
    if: ${{ needs.check_version_back.outputs.deploy == 'true' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front:
    name: Deploy front
    needs: [check_version_front, deploy_back]
    if: ${{ needs.check_version_front.outputs.deploy == 'true' && needs.deploy_back.result != 'failure' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app:
    name: Deploy app
    needs: [check_version_app, deploy_front, deploy_back]
    if: ${{ needs.check_version_app.outputs.deploy == 'true' && needs.deploy_back.result != 'failure' && needs.deploy_front.result != 'failure' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  deploy_back_retry1:
    name: 'Deploy back: retry 1'
    needs: deploy_back
    if: ${{ needs.deploy_back.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_retry1:
    name: 'Deploy front: retry 1'
    needs: deploy_front
    if: ${{ needs.deploy_front.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app_retry1:
    name: 'Deploy app: retry 1'
    needs: deploy_app
    if: ${{ needs.deploy_app.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  deploy_back_retry2:
    name: 'Deploy back: retry 2'
    needs: deploy_back_retry1
    if: ${{ needs.deploy_back_retry1.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_retry2:
    name: 'Deploy front: retry 2'
    needs: deploy_front_retry1
    if: ${{ needs.deploy_front_retry1.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app_retry2:
    name: 'Deploy app: retry 2'
    needs: deploy_app_retry1
    if: ${{ needs.deploy_app_retry1.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  deploy_back_retry3:
    name: 'Deploy back: retry 3'
    needs: deploy_back_retry2
    if: ${{ needs.deploy_back_retry2.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_retry3:
    name: 'Deploy front: retry 3'
    needs: deploy_front_retry2
    if: ${{ needs.deploy_front_retry2.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app_retry3:
    name: 'Deploy app: retry 3'
    needs: deploy_app_retry2
    if: ${{ needs.deploy_app_retry2.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  deploy_back_retry4:
    name: 'Deploy back: retry 4'
    needs: deploy_back_retry3
    if: ${{ needs.deploy_back_retry3.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_retry4:
    name: 'Deploy front: retry 4'
    needs: deploy_front_retry3
    if: ${{ needs.deploy_front_retry3.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app_retry4:
    name: 'Deploy app: retry 4'
    needs: deploy_app_retry3
    if: ${{ needs.deploy_app_retry3.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  deploy_back_retry5:
    name: 'Deploy back: retry 5'
    needs: deploy_back_retry4
    if: ${{ needs.deploy_back_retry4.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_retry5:
    name: 'Deploy front: retry 5'
    needs: deploy_front_retry4
    if: ${{ needs.deploy_front_retry4.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main

  deploy_app_retry5:
    name: 'Deploy app: retry 5'
    needs: deploy_app_retry4
    if: ${{ needs.deploy_app_retry4.result == 'failed' && !cancelled() }}
    uses: test-ci-workflows-israel/app/.github/workflows/prod.yml@main

  rollback_back:
    name: Rollback back
    needs: deploy_back_retry5
    if: ${{ needs.deploy_back_retry5.result == 'failure' && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rollback back"

  rollback_front:
    name: Rollback front
    needs: deploy_front_retry5
    if: ${{ needs.deploy_front_retry5.result == 'failure' && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rollback front"

  deploy_back_rollback:
    name: 'Deploy back: rollback'
    needs: rollback_back
    if: ${{ needs.rollback_back.result == 'failure' && !cancelled() }}
    uses: test-ci-workflows-israel/back/.github/workflows/prod.yml@main

  deploy_front_rollback:
    name: 'Deploy front: rollback'
    needs: rollback_front
    if: ${{ needs.rollback_front.result == 'failure' && !cancelled() }}
    uses: test-ci-workflows-israel/front/.github/workflows/prod.yml@main
## https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
